name: Combined CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '44 10 * * 4'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codeql-analysis:
    name: Analyze CodeQL (${{ matrix.language }})
    runs-on: ${{ matrix.language == 'swift' && 'macos-latest' || 'ubuntu-latest' }}
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - language: java-kotlin
            build-mode: manual  # Changed to manual for better control
          - language: javascript-typescript
            build-mode: none
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        if: matrix.language == 'java-kotlin'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
          queries: security-extended,security-and-quality

      # Autobuild attempts to build any compiled languages
      - name: Autobuild
        if: matrix.build-mode == 'none'
        uses: github/codeql-action/autobuild@v3

      # Manual build for Java/Kotlin
      - name: Manual Build
        if: matrix.language == 'java-kotlin'
        run: |
          cd BackEnd/alttabjournal
          mvn clean compile

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"

  spring-boot-ci:
    name: Spring Boot CI Checks
    runs-on: ubuntu-latest
    needs: codeql-analysis
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Install Dependencies
        working-directory: BackEnd/alttabjournal
        run: mvn install -DskipTests

      - name: Check Code Style
        working-directory: BackEnd/alttabjournal
        run: mvn checkstyle:check

      - name: Run Unit Tests
        working-directory: BackEnd/alttabjournal
        run: mvn test

      - name: Build Application
        working-directory: BackEnd/alttabjournal
        run: mvn package

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app
          path: BackEnd/alttabjournal/target/*.jar
