name: React CI Checks

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd FrontEnd/alttabjournal
          npm install

      - name: Lint Code
        run: |
          cd FrontEnd/alttabjournal
          npm run lint

      - name: Run Unit Tests
        run: |
          cd FrontEnd/alttabjournal
          npm run test

      - name: Build React App
        run: |
          cd FrontEnd/alttabjournal
          npm run build